# -*- coding: utf-8 -*-
"""Copy of WORD@VEC

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ych69yEUn9brH3h0t0MQWZnJuK17rmJt
"""

import gensim
import pandas as pd
import nltk
from nltk.corpus import brown
nltk.download('brown')

data=pd.read_csv('brown.csv')

data.head()

sentences = brown.sents()
model = gensim.models.Word2Vec(sentences, min_count=1)
model.save('brown_model')
print("Brown corpus model saved.")

model = gensim.models.Word2Vec.load('brown_model')
#words most similar to mother
print(model.most_similar('mother'))

print(model['human'])

print(model['father'])

print('sentence: ', sentences[2])

data.shape

data[['filename']].describe()